### ISSUE TITLE
Support for other linux distors - I'm ready to contribute

### ISSUE THREAD

**Issue by fayaz-modz** [lzhiyong/termux-ndk#137]
I've been trying to port android ndk to aarch64, and in the process I found your repository. First off, Thank You for making such an amazing port.

I think it is clear that termux-ndk only supports termux. I tried running this on ubuntu but no luck. I understand that you do not plan to have this running on linux as a general platform.

But I am really in need of this support right now. I would like to know how you ported this to termux. So that I can do the same for linux/arm64 in general. I am ready to collaborate if you will or we can mainatain  a different repo altogether supporting linux/arm64.

If you cant find time, please let me know how you have done this. The tutorials in this repo isn't so clear about how you approached to porting. I would like for a clear roadmap to porting not a general answer. like:
what machine did you use to compile this (I'm trying to use c6g.xlarge instance on aws which is based on arm architecture)
etc...

Thank You.

**Comment by lzhiyong** [comment]
I haven't tried compiling for linux/arm64 yet, so I can't help you now. Essentially, we only need to port `llvm+clang,` and don't need to start from scratch. Libraries like `sysroot` and `runtimes` don't need to be recompiled because they are pre-compiled libraries on the Android platform.

I don't know how to explain these steps clearly, but you can start from `build.py` and figure it out step by step, because that's how I did it too.

**Comment by zongou** [comment]
it turns out we dont need to compile anything. you can simply donwload andorid ndk for linux-x86_64 and download prebuilt clang toolchain for arm64, rename dir linxu-x86_64 to linux-aarch64, and copy all the files under llvm toolchain bin, it will just work
```sh
/home/user/android-ndk-r26b/toolchains/llvm/prebuilt/linux-aarch64/
├── AndroidVersion.txt
├── MODULE_LICENSE_APACHE2
├── MODULE_LICENSE_BSD_LIKE
├── MODULE_LICENSE_MIT
├── NOTICE
├── bin
├── clang_source_info.md
├── include
├── lib
├── libexec
├── linux-aarch64
├── linux-x86_64
├── manifest_10552028.xml
├── musl
├── prebuilt_include
├── python3
├── share
└── sysroot
```
if you can not figure it out, try this tool
https://github.com/shengyun-zhou/llvm-cross-toolchains#4-build-and-assemble-toolchain

to run directly on android, i think we can either try build llvm toolchain for android with ndk, it is not hard, or try figuring out a way to make zig toolchain support it, i have tested that zig toolchain can run on android

**Comment by dhuux** [comment]
> it turns out we dont need to compile anything. you can simply donwload andorid ndk for linux-x86_64 and download prebuilt clang toolchain for arm64, rename dir linxu-x86_64 to linux-aarch64, and copy all the files under llvm toolchain bin, it will just work
> 
> ```shell
> /home/user/android-ndk-r26b/toolchains/llvm/prebuilt/linux-aarch64/
> ├── AndroidVersion.txt
> ├── MODULE_LICENSE_APACHE2
> ├── MODULE_LICENSE_BSD_LIKE
> ├── MODULE_LICENSE_MIT
> ├── NOTICE
> ├── bin
> ├── clang_source_info.md
> ├── include
> ├── lib
> ├── libexec
> ├── linux-aarch64
> ├── linux-x86_64
> ├── manifest_10552028.xml
> ├── musl
> ├── prebuilt_include
> ├── python3
> ├── share
> └── sysroot
> ```
> 
> if you can not figure it out, try this tool https://github.com/shengyun-zhou/llvm-cross-toolchains#4-build-and-assemble-toolchain
> 
> to run directly on android, i think we can either try build llvm toolchain for android with ndk, it is not hard, or try figuring out a way to make zig toolchain support it, i have tested that zig toolchain can run on android



bro i tried this on termux for the sake of trying and i have no linux or programming knowledge so i was hoping you could help this. the are glibc packages for Termux which makes us natively run aarch64/linux binaries on Termux as long as the binary doesn't include some hardcoded paths. so i  tried to build an example app but it failed in the middle of compilation. the build completes when i change the ndk path to lzhiyong's ndk though. this is what i did: i downloaded `ndk for linux-86_64`. then downloaded `clang/llvm for aarch64`. then extracted and patchelfed the clang/llvm binaries in the `bin` dir, all at once. moved them to `/toolchains/llvm/prebuilt/linux-x86_64/bin`.  i also replaced `make` `vsyasm`  `ytasm` ` yasm` tools in `/android-ndk-r26b/prebuilt/linux-x86_64/bin` with patched linux/aarch64 glibc based onces. i think there other ndk tools that need to be fixed for this to work.  and the some elfs in `/ndk/shader-tools` folder are still x86_64 though @lzhiyong  said only llvm+clang needs to be ported. 

 build failed here:
![Screenshot_20231114-145511_Termux](https://github.com/lzhiyong/termux-ndk/assets/63465816/e4af988c-ea6b-400a-9dd0-26ceaa876eaf)

patchelfed glibc based clang-17 binary on termux.
![Screenshot_20231114-162119_Termux](https://github.com/lzhiyong/termux-ndk/assets/63465816/a02779b0-894f-48cc-ac21-cd558d5ab2de)
