### ISSUE TITLE
Ndk for arm (32bit)

### ISSUE THREAD

**Issue by RohitKushvaha01** [lzhiyong/termux-ndk#154]
Can you please compile this ndk for arm?

**Comment by iudah** [comment]
Lzhiyong has pointed out that we don't to recompile the entire ndk
"since google already built most of it. so we only need to ~build the llvm toolchain, then~ replace the llvm inside NDK."

All you need is to replace the clang packages in the nkd with their termux equilvalent, assuming you already have clang installed.

You may try this [script](https://github.com/iudah/AndroidIDE-NDK-ARMv8l/) I wrote. Although it is for [AndroidIDE](https://github.com/AndroidIDEOfficial/AndroidIDE), it should work on clang.
